---
- name: checks if redis is installed
  command: redis-server -v
  register: redis_installed
  ignore_errors: yes

- name: Add redis repository
  apt_repository:
    repo: 'ppa:rwky/redis'
  when: redis_installed|failed

- name: Install redis from package
  apt:
    name: redis-server
    state: latest
    update_cache: yes
  when: redis_installed|failed

- name: Create data directory
  file:
    state: directory
    path: "{{ redis.config.dir }}"
    owner: "{{ redis.user }}"
    group: "{{ redis.group }}"
    recurse: yes

- name: Install config
  template:
    src: redis.conf.j2
    dest: "{{ redis.config_path }}"
  notify:
    - restart redis

- name: Ensure redis-server started and enabled
  service:
    name: redis-server
    state: started
    enabled: yes

- name: Add Redis monit config
  template:
    src: redis_monit.j2
    dest: "/etc/monit/conf.d/redis-server"
  notify:
    - restart redis